# Metadata about this component, to be used in the CMS
spec:
  label: hero
  description: Page hero component
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  title-text: "We are outrun."
  type: standard
  color: pink
  button: 
    bookshop:element/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title-text: "We are outrun."
  type: standard
  color: pink

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  type:
    type: select
    options:
      values:
        - standard
        - short
