# Metadata about this component, to be used in the CMS
spec:
  label: text
  description: Text markdown component
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  htmlBlock: "<p>We are outrun.</p>"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  htmlBlock: "<p>We are outrun.</p>"