# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Button
  description: The primary CTA button.
  icon: smart_button
  tags: [button]

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Button"
  background: "Pink"
  border: "Light"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: "Button"
  background: "Pink"
  border: "Light"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    type: select
    options:
      values:
        - Pink
        - Yellow
  border:
    type: select
    options:
      values:
        - Light
        - Dark
